name: Build APKs (Debug)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-universal:
    name: Build Universal (64-bit) Debug
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java and Android SDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build universal debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleFossDebug \
            --init-script .github/init-scripts/abi-foss-universal-64bit.gradle \
            --no-build-cache --rerun-tasks

      - name: Rename APK
        run: |
          mkdir -p ${{ runner.temp }}/apks
          APK=$(find music/ -name "*.apk" | head -n 1)
          mv "$APK" "${{ runner.temp }}/apks/felicity-foss-universal-debug.apk"

      - name: Upload universal APK
        uses: actions/upload-artifact@v4
        with:
          name: felicity-foss-universal-debug
          path: ${{ runner.temp }}/apks/felicity-foss-universal-debug.apk
          retention-days: 1
          if-no-files-found: error
